services:
  - type: web
    name: strapi
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: postgres
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: CLOUDINARY_NAME
        value: dkciswqw8
      - key: CLOUDINARY_KEY
        value: 729297395215962
      - key: CLOUDINARY_SECRET
        sync: false

databases:
  - name: strapi
    plan: free